using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; // Add this namespace
using Mutagen.Bethesda.Plugins;
using System.ComponentModel;
using Mutagen.Bethesda.WPF.Reflection.Attributes;
using Synthesis.Bethesda.Commands;

namespace unofficialReqtificatorLite
{
    public record Settings
    {
		[SettingName("****MANUAL PATCHING****: If not using Auto-Patching, select mods here:")]
        public List<ModKey> TargetMods = new List<ModKey>();

        [SettingName("Patch Actors")]
        public bool ActorOn { get; set; } = true; // Default is on

        [SettingName("Patch Armor")]
        public bool ArmorOn { get; set; } = true; // Default is on

        [SettingName("Patch Weapons")]
        public bool WeaponsOn { get; set; } = true; // Default is on

        [SettingName("Patch Arrows and Bolts")]
        public bool ArrowsOn { get; set; } = true; // Default is on

        [SettingName("Patch Doors")]
        public bool DoorsOn { get; set; } = true; // Default is on

        [SettingName("Patch Containers")]
        public bool ContOn { get; set; } = true; // Default is on

        [SettingName("Disable SPID/KID Distribution. Attach Perks, Spells, and Keywords to actual records. (Warning: Will take longer to generate.)")]
        public bool spidOn { get; set; } = false; // Default is off

        [SettingName("Max Number of Plugins to Attempt to Patch. (Hover here for more details.)"),
            Tooltip("Any plugin generated by synthesis that will have over 254 masters will fail to be created."+
			"\nThe Reqtificator Lite will attempt to stop before this limit so that the plugin generated can be saved."+
			"\nPatching can then continue in a new Synthesis plugin. The Reqtifcator lite will continue exactly where it left off."+
			"\nThis Number determines the maximum amount of plugins that will be attempted to be patched by a single plugin."
			)]
	   public int maxNumP { get; set; } = 200;


        [SettingName("****AUTO-PATCHING****: All plugins NOT in Requiem for the Indifferent.esp. (Hover here for more details.)"),
            Tooltip("If enabled, the Reqtificator Lite will automatically patch any plugin that has not been patched by Requiem for the Indifferent.esp" +
            "\nYou would not need to select any plugins below." +
            "\nIf you want to patch only specific plugnins, leave this option disabled.")]
        public bool ReqOn { get; set; } = false; // Default is of
		
		[SettingName("****AUTO-PATCHING****: All plugins NOT in ReqLite_IgnoreThesePlugins.txt (Hover here for more details.)"),
            Tooltip("If enabled, the Reqtificator Lite will automatically patch any plugin that is not in ReqLite_IgnoreThesePlugins.txt " +
            "\nYou would not need to select any plugins below." +
            "\nIf you want to patch only specific plugnins, leave this option disabled.")]
        public bool txtOn { get; set; } = false; // Default is of


    }

    





}

